
PACKET_LENGTH_BYTES = 1
PACKET_DATA_BYTES   = 16
PACKET_CRC_BYTES    = 1
PACKET_TOTAL_BYTES  = PACKET_LENGTH_BYTES + PACKET_DATA_BYTES + PACKET_CRC_BYTES
PACKET_CRC_INDEX    = PACKET_LENGTH_BYTES + PACKET_DATA_BYTES

PACKET_ACK_DATA0    = 0x15
PACKET_RETX_DATA0   = 0x19
PACKET_NACK_DATA0   = 0x79

baudRate = 9600
DataBits = 8
StopBits = 1
Parity  = 'N'
